NiewidzialnaPomoc/NiewidzialnaPomoc/Controllers/RewardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Repository.Models;
using Microsoft.AspNet.Identity;
using Repository.Models.Views;

namespace NiewidzialnaPomoc.Controllers
{
    public class RewardsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Rewards
        public ActionResult Index()
        {
            //var rewards = db.Rewards.Where(r => r.RewardCodes.Any(rc => rc.IsUsed == false));
            //return View(rewards.ToList());

            Session["rewardCodeId"] = null;

            var rewards = db.Rewards.Where(r => r.RewardCodes.Any(rc => rc.IsUsed == false));
            var user = db.ApplicationUsers.Find(User.Identity.GetUserId());

            RewardsViewModel viewModel = new RewardsViewModel();
            viewModel.Rewards = new List<Reward>();
            viewModel.Rewards = rewards.ToList();
            viewModel.ApplicationUser = user;

            return View(viewModel);

        }

        public ActionResult RewardCode(int? id)
        {
            Reward reward = db.Rewards.Find(id);
            var user = db.ApplicationUsers.Find(User.Identity.GetUserId());

            if(user == null)
            {

                TempData["alert"] = "<script>alert('Musisz być zalogowany aby uzyskać nagrodę.');</script>";
                return RedirectToAction("Index");
            }

            if(user.Points < reward.Price && Session["rewardCodeId"] == null)
            {
                TempData["alert"] = "<script>alert('Nie masz wystarczającej ilości punktów.');</script>";
                return RedirectToAction("Index");
            }

            RewardCode rewardCode;

            if (Session["rewardCodeId"] == null)
            {
                rewardCode = reward.RewardCodes.First(r => r.IsUsed == false);

                Session["rewardCodeId"] = rewardCode.Id;

                var rc = db.RewardCodes.Find(rewardCode.Id);
                rc.IsUsed = true;
                rc.RewardOwnerId = user.Id;
                rc.ReceivedDate = DateTime.Now;

                user.Points -= rc.Reward.Price;

                db.SaveChanges();
            }
            else
            {
                rewardCode = db.RewardCodes.Find(Session["rewardCodeId"]);
            }

            return View(rewardCode);
        }

    }
}

NiewidzialnaPomoc/NiewidzialnaPomoc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery-ui-1.12.0.js"></script>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle"
                        data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Niewidzialna pomoc", "Index", "Home",
               new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("O stronie", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Nagrody", "Rewards", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Dodaj ogłoszenie",
                           "CreateAdvertisement", "Home")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>