NiewidzialnaPomoc/NiewidzialnaPomoc/Models/Advertisement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace NiewidzialnaPomoc.Models
{
    public class Advertisement
    {
        public Advertisement()
        {
            this.Categories = new HashSet<Category>();
            this.Helpers = new HashSet<ApplicationUser>();
        }

        public int Id { get; set; }

        [Display(Name = "Tytuł ogłoszenia:")]
        [MaxLength(72)]
        public string Title { get; set; }

        [Display(Name = "Treść ogłoszenia:")]
        [MaxLength(500)]
        public string Content { get; set; }

        [Display(Name = "Data dodania:")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime AddDate { get; set; }

        public int AuthorId { get; set; }

        public int LocationId { get; set; }

        public bool IsFinished { get; set; }

        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<ApplicationUser> Helpers { get; set; }
        public virtual ApplicationUser Author { get; set; }
        public virtual Location Location { get; set; }
    }
}

NiewidzialnaPomoc/NiewidzialnaPomoc/Controllers/AdvertisementPhotoController.cs
using Repository.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NiewidzialnaPomoc.Controllers
{
    public class AdvertisementPhotoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AdvertisementPhoto
        public ActionResult Index(int id, bool thumbnail)
        {
            var photoToRetrieve = db.AdvertisementPhotos.Find(id);

            if (thumbnail == true)
            {
                Image i;
                using (MemoryStream ms = new MemoryStream())
                {
                    ms.Write(photoToRetrieve.FileContent, 0, 
                        photoToRetrieve.FileContent.Length);
                    i = Image.FromStream(ms);
                }

                var imageWidth = i.Width;
                var imageHeight = i.Height;

                double maxWidth = 240;
                double maxHeight = 160;

                if (i.Width > maxWidth || i.Height > maxHeight)
                {
                    double scale;
                    double divider = maxWidth / maxHeight;
                    if (i.Width >= i.Height * divider)
                    {
                        scale = i.Width / maxWidth;
                    }
                    else
                    {
                        scale = i.Height / maxHeight;
                    }

                    imageWidth = System.Convert.ToInt32(Math.Floor(i.Width / scale));
                    imageHeight = System.Convert.ToInt32(Math.Floor(i.Height / scale));
                }

                return File(imageToByteArray(i.GetThumbnailImage(imageWidth, 
                    imageHeight, () => false, IntPtr.Zero)), photoToRetrieve.ContentType);
            }
            else
            {
                return File(photoToRetrieve.FileContent, photoToRetrieve.ContentType);
            }
        }

        public byte[] imageToByteArray(Image imageIn)
        {
            MemoryStream ms = new MemoryStream();
            imageIn.Save(ms, System.Drawing.Imaging.ImageFormat.Jpeg);
            return ms.ToArray();
        }
    }
}

NiewidzialnaPomoc/NiewidzialnaPomoc/Controllers/AdvertisementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Repository.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using Repository.Models.Views;

namespace NiewidzialnaPomoc.Controllers
{
    public class AdvertisementsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Advertisements

        public ActionResult Index(AdvertisementsListViewModel viewModel, string sortOrder, int? page)
        {
            if (viewModel.AdvertisementSearchModel == null)
            {
                viewModel.AdvertisementSearchModel = new AdvertisementSearchModel();
                if(Session["SearchViewModel"] != null)
                {
                    viewModel.AdvertisementSearchModel = 
                        (AdvertisementSearchModel)Session["SearchViewModel"];
                }
            }
            else
            {
                Session["SearchViewModel"] = viewModel.AdvertisementSearchModel;
            }

            //Categories
            var selectedCategories = new List<Category>();
            var postedCategoryIds = new string[0];

            if (viewModel.AdvertisementSearchModel.PostedCategories == null)
            {
                viewModel.AdvertisementSearchModel.PostedCategories = 
                    new PostedCategories();

            }

            if (viewModel.AdvertisementSearchModel.PostedCategories.CategoriesIds != null)
            {
                postedCategoryIds = 
                    viewModel.AdvertisementSearchModel.PostedCategories.CategoriesIds;
            }

            if (postedCategoryIds.Any())
            {
                selectedCategories = db.Categories.Where(x => 
                postedCategoryIds.Any(s => x.Id.ToString().Equals(s))).ToList();
            }

            viewModel.AvaibleCategories = new List<CategoryViewModel>();
            var categories = db.Categories;
            foreach (Category c in categories)
            {
                var cvm = new CategoryViewModel();
                cvm.Id = c.Id;
                cvm.Name = c.Name;
                viewModel.AvaibleCategories.Add(cvm);
            }

            viewModel.SelectedCategories = new List<CategoryViewModel>();
            foreach (Category c in selectedCategories)
            {
                var cvm = new CategoryViewModel();
                cvm.Id = c.Id;
                cvm.Name = c.Name;
                viewModel.SelectedCategories.Add(cvm);
            }

            //Difficulties

            var selectedDifficulties = new List<Difficulty>();
            var postedDifficultyIds = new string[0];
            if (viewModel.AdvertisementSearchModel.PostedDifficulties == null)
            {
                viewModel.AdvertisementSearchModel.PostedDifficulties = new PostedDifficulties();

            }

            if (viewModel.AdvertisementSearchModel.PostedDifficulties.DifficultiesIds != null)
            {
                postedDifficultyIds = viewModel.AdvertisementSearchModel.PostedDifficulties.DifficultiesIds;
            }

            if (postedDifficultyIds.Any())
            {
                selectedDifficulties = db.Difficulties.Where(x => postedDifficultyIds.Any(s => x.Id.ToString().Equals(s))).ToList();
            }

            viewModel.AvaibleDifficulties = new List<DifficultyViewModel>();
            var difficulties = db.Difficulties;
            foreach (Difficulty d in difficulties)
            {
                var dvm = new DifficultyViewModel();
                dvm.Id = d.Id;
                dvm.Name = d.Name;
                viewModel.AvaibleDifficulties.Add(dvm);
            }

            viewModel.SelectedDifficulties = new List<DifficultyViewModel>();
            foreach (Difficulty d in selectedDifficulties)
            {
                var dvm = new DifficultyViewModel();
                dvm.Id = d.Id;
                dvm.Name = d.Name;
                viewModel.SelectedDifficulties.Add(dvm);
            }

            //Locations
            viewModel.Locations = new List<Location>();
            viewModel.Locations = db.Locations.ToList();

            //Advertisements
            var searchLogic = new AdvertisementsSearchLogic();
            var advertisements = searchLogic.GetAdvertisements(viewModel.AdvertisementSearchModel);

            //Sorting
            ViewBag.CurrentSort = sortOrder;
            ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.LocationSortParm = 
                sortOrder == "location_asc" ? "location_desc" : "location_asc";
            ViewBag.AddDateSortParm = 
                sortOrder == "addDate_asc" ? "addDate_desc" : "addDate_asc";
            ViewBag.DifficultySortParm = 
                sortOrder == "difficulty_asc" ? "difficulty_desc" : "difficulty_asc";

            switch (sortOrder)
            {
                case "title_desc":
                    advertisements = advertisements.OrderByDescending(a => a.Title);
                    break;
                case "location_asc":
                    advertisements = advertisements.OrderBy(a => a.Location.Name);
                    break;
                case "location_desc":
                    advertisements = advertisements.OrderByDescending(a => a.Location.Name);
                    break;
                case "addDate_asc":
                    advertisements = advertisements.OrderBy(a => a.AddDate);
                    break;
                case "addDate_desc":
                    advertisements = advertisements.OrderByDescending(a => a.AddDate);
                    break;
                case "difficulty_asc":
                    advertisements = advertisements.OrderBy(a => a.Difficulty.Name);
                    break;
                case "difficulty_desc":
                    advertisements = advertisements.OrderByDescending(a => a.Difficulty.Name);
                    break;
                default:
                    advertisements = advertisements.OrderBy(a => a.Title);
                    break;
            }

            int pageSize = 2;
            int pageNumber = (page ?? 1);
            viewModel.Advertisements = advertisements.ToPagedList(pageNumber, pageSize);

            return View(viewModel);
        }

        // GET: Advertisements/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisement advertisement = db.Advertisements.Find(id);
            if (advertisement == null)
            {
                return HttpNotFound();
            }
            return View(advertisement);
        }
    }
}

NiewidzialnaPomoc/NiewidzialnaPomoc/Views/Advertisements/Details.cshtml
@model Repository.Models.Advertisement

@{
    ViewBag.Title = Model.Title;
}

<h2>@ViewBag.Title</h2>

<div>
    <div class="col-md-8" style="padding:0px;">
        <div>
            <strong>@Html.DisplayFor(model => model.Location.Name)</strong> |
            Data dodania: @Html.DisplayFor(model => model.AddDate) |
            Trudność: @Html.DisplayFor(model => model.Difficulty.Name)
        </div>
        <br />
        <div>
            @Html.DisplayFor(model => model.Content)
        </div>
        <br />
        <div>
            @if (Model.AdvertisementPhotos.Any())
            {
                foreach (var p in Model.AdvertisementPhotos)
                {
                    <a href="">
                        <img src="~/AdvertisementPhoto?id=@p.Id&thumbnail=true" alt="photo" 
                             onclick="javascript:window.open('@(Url.Action("Index", "AdvertisementPhoto", new { id = p.Id, thumbnail = false}))')" />
                    </a>
                }
            }
            else
            {
                <img src="~/DefaultPhoto?id=2" alt="photo" />
            }
        </div>
        <br />
        <div>
            @Html.ActionLink("Powrót", "Index")
        </div>
    </div>
    <div class="col-md-4">
        @if (Model.Author.Avatar != null)
        {
            <div>
                <img src="~/Avatar?id=@Model.Author.Avatar.Id" alt="avatar" />
            </div>
        }
        else
        {
            <div>
                <img src="~/DefaultPhoto?id=1" alt="photo" />
            </div>
        }
        <div>
            <h4>@Html.DisplayFor(model => model.Author.FullName)</h4>
            <h6>Email: @Html.DisplayFor(model => model.Author.Email)</h6>
            @if (Model.Author.PhoneNumber != null)
            {
                <h6>Telefon: @Html.DisplayFor(model => model.Author.PhoneNumber)</h6>
            }
        </div>
    </div>
</div>

NiewidzialnaPomoc/NiewidzialnaPomoc/Views/Advertisements/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model  Repository.Models.Views.AdvertisementsListViewModel

@{
    ViewBag.Title = "Lista ogłoszeń";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm(FormMethod.Get))
{
    <div id="search-container">
        @Html.TextBoxFor(model => model.AdvertisementSearchModel.TitleContent,
       htmlAttributes: new { @class = "form-control" })
        @Html.DropDownListFor(model => model.AdvertisementSearchModel.LocationId,
       new SelectList(Model.Locations, "Id", "Name"), "",
       htmlAttributes: new { @class = "form-control", @style = "width:150px;" })
        <button type="submit" class="btn btn-primary">Szukaj</button>
    </div>
    <div>
        <h4>@Html.DisplayNameFor(model => 
        model.AvaibleCategories.FirstOrDefault().Name)</h4>
        @Html.CheckBoxListFor(model => 
        model.AdvertisementSearchModel.PostedCategories.CategoriesIds,
        model => model.AvaibleCategories,
        category => category.Id,
        category => category.Name,
        model => model.SelectedCategories)
    </div>
    <div>
        <h4>@Html.DisplayNameFor(model => 
        model.AvaibleDifficulties.FirstOrDefault().Name)</h4>
        @Html.CheckBoxListFor(model => 
        model.AdvertisementSearchModel.PostedDifficulties.DifficultiesIds,
        model => model.AvaibleDifficulties,
        difficulty => difficulty.Id,
        difficulty => difficulty.Name,
        model => model.SelectedDifficulties)
    </div>
}
<div id="sorting-container">
    <p>Sortowanie: 
    @Html.ActionLink(Html.DisplayNameFor(model =>
        model.Advertisements.FirstOrDefault().Title).ToHtmlString(),
        "Index", new { sortOrder = ViewBag.TitleSortParm }) |
    @Html.ActionLink(Html.DisplayNameFor(model => 
        model.Advertisements.FirstOrDefault().Location.Name).ToHtmlString(), 
        "Index", new { sortOrder = ViewBag.LocationSortParm }) |
    @Html.ActionLink(Html.DisplayNameFor(model => 
        model.Advertisements.FirstOrDefault().AddDate).ToHtmlString(), 
        "Index", new { sortOrder = ViewBag.AddDateSortParm }) |
    @Html.ActionLink(Html.DisplayNameFor(model => 
        model.Advertisements.FirstOrDefault().Difficulty.Name).ToHtmlString(), 
        "Index", new { sortOrder = ViewBag.DifficultySortParm })</p>
</div>
<br />
<table class="table">
    @foreach (var item in Model.Advertisements)
    {
        <tr class="clickable-row" onclick="location.href = '@(Url.Action("Details", "Advertisements", new { id = item.Id }))'">
            <td>
                <div class="col-md-3">
                    @if (item.AdvertisementPhotos.Any())
                    {
                        <img src="~/AdvertisementPhoto?id=
                             @item.AdvertisementPhotos.FirstOrDefault().Id&thumbnail=true"
                             alt="photo" />
                    }
                    else
                    {
                        <img src="~/DefaultPhoto?id=2" alt="photo" />
                    }   
                </div>
                <div class="col-md-9">
                    <h4>@Html.DisplayFor(modelItem => item.Title)</h4>
                    <h5>@Html.DisplayFor(modelItem => item.Location.Name)</h5>
                    <h6>Data dodania: @Html.DisplayFor(modelItem => item.AddDate)</h6>
                    <h6>Trudność: @Html.DisplayFor(modelItem => item.Difficulty.Name)</h6>
                </div>
            </td>
        </tr>
    }

</table>
<br />
Strona @(Model.Advertisements.PageCount < Model.Advertisements.PageNumber ?
        0 : Model.Advertisements.PageNumber) z @Model.Advertisements.PageCount
@Html.PagedListPager(Model.Advertisements, 
    page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort }))